[package]
name = "server_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
futures = "0.3"

rusqlite = { version = "0.32.0", features = ["bundled"] }
r2d2 = "0.8"
r2d2_sqlite = "0.25"
env_logger = "0.11"